// exercises/phrase_practice/hiragana_phrases.js

const hiraganaPhrases = [
  {
    phrase: "わたしはがくせいです",
    transcriptionRu: "ва~та~си~ва га~ку~сэ~й дэ~с",
    translationRu: "Я студент",
    transcriptionEn: "wa~ta~shi wa ga~ku~se~i de~su",
    translationEn: "I am a student",
  },
  {
    phrase: "これはほんです",
    transcriptionRu: "ко~рэ~ва хон дэ~с",
    translationRu: "Это книга",
    transcriptionEn: "ko~re wa hon de~su",
    translationEn: "This is a book",
  },
  {
    phrase: "すしをたべますか",
    transcriptionRu: "су~си~о та~бэ~ма~с~ка",
    translationRu: "Будешь есть суши?",
    transcriptionEn: "su~shi~o ta~be~ma~su~ka",
    translationEn: "Will you eat sushi?",
  },
  {
    phrase: "いただきます",
    transcriptionRu: "и~та~да~ки~ма~с",
    translationRu: "Приятного аппетита (перед едой)",
    transcriptionEn: "i~ta~da~ki~ma~su",
    translationEn: "Let's eat / bon appétit",
  },
  {
    phrase: "ごちそうさまでした",
    transcriptionRu: "го~ти~со~у~са~ма~де~си~та",
    translationRu: "Спасибо за угощение (после еды)",
    transcriptionEn: "go~chi~so~u~sa~ma~de~shi~ta",
    translationEn: "Thank you for the meal",
  },
  {
    phrase: "わたしのなまえはさくらです",
    transcriptionRu: "ва~та~си~но на~ма~э~ва са~ку~ра дэ~с",
    translationRu: "Меня зовут Сакура",
    transcriptionEn: "wa~ta~shi no na~ma~e wa sa~ku~ra de~su",
    translationEn: "My name is Sakura",
  },
  {
    phrase: "おはようございます",
    transcriptionRu: "о~ха~йо~у го~за~й~ма~с",
    translationRu: "Доброе утро",
    transcriptionEn: "o~ha~yo~u go~za~i~ma~su",
    translationEn: "Good morning",
  },
  {
    phrase: "こんにちわ",
    transcriptionRu: "ко~н~ни~чи~ва",
    translationRu: "Добрый день",
    transcriptionEn: "ko~n~ni~chi~wa",
    translationEn: "Hello / Good afternoon",
  },
  {
    phrase: "こんばんは",
    transcriptionRu: "ко~н~ба~н~ва",
    translationRu: "Добрый вечер",
    transcriptionEn: "ko~n~ban~wa",
    translationEn: "Good evening",
  },
  {
    phrase: "さようなら",
    transcriptionRu: "са~йо~у~на~ра",
    translationRu: "До свидания",
    transcriptionEn: "sa~yo~u~na~ra",
    translationEn: "Goodbye",
  },
  {
    phrase: "ありがとう",
    transcriptionRu: "а~ри~га~то",
    translationRu: "Спасибо",
    transcriptionEn: "a~ri~ga~to",
    translationEn: "Thank you",
  },
  {
    phrase: "すみません",
    transcriptionRu: "су~ми~ма~сэн",
    translationRu: "Извините / Простите",
    transcriptionEn: "su~mi~ma~sen",
    translationEn: "Excuse me / I'm sorry",
  },
  {
    phrase: "がんばってください",
    transcriptionRu: "га~н~ба~ттэ ку~да~са~й",
    translationRu: "Удачи / Постарайся!",
    transcriptionEn: "ga~n~ba~tte ku~da~sa~i",
    translationEn: "Do your best / Good luck",
  },
  {
    phrase: "だいじょうぶですか",
    transcriptionRu: "да~й~дзё~у~бу дэ~с~ка",
    translationRu: "Всё в порядке?",
    transcriptionEn: "da~i~jo~u~bu de~su~ka",
    translationEn: "Are you okay?",
  },
  {
    phrase: "いってきます",
    transcriptionRu: "и~т~тэ~ки~ма~с",
    translationRu: "Я пошёл (говорят, уходя из дома)",
    transcriptionEn: "i~t~te~ki~ma~su",
    translationEn: "I'm off / I'll go and come back",
  },
];
