// exercises/phrase_practice/hiragana_phrases.js

const hiraganaPhrases = [
  {
    phrase: "わたしはがくせいです",
    transcriptionRu: "ва~та~си~ва га~ку~сэ~й дэ~с",
    translationRu: "Я студент",
    transcriptionEn: "wa~ta~shi wa ga~ku~se~i de~su",
    translationEn: "I am a student",
    wordsRu: [
      "わたし (watashi) - я",
      "は (wa) - частица темы",
      "がくせい (gakusei) - студент",
      "です (desu) - глагол-связка",
    ],
    wordsEn: [
      "わたし (watashi) - I",
      "は (wa) - topic particle",
      "がくせい (gakusei) - student",
      "です (desu) - am/is",
    ],
  },
  {
    phrase: "これはほんです",
    transcriptionRu: "ко~рэ~ва хон дэ~с",
    translationRu: "Это книга",
    transcriptionEn: "ko~re wa hon de~su",
    translationEn: "This is a book",
    wordsRu: [
      "これ (kore) - это",
      "は (wa) - частица темы",
      "ほん (hon) - книга",
      "です (desu) - глагол-связка",
    ],
    wordsEn: [
      "これ (kore) - this",
      "は (wa) - topic particle",
      "ほん (hon) - book",
      "です (desu) - is",
    ],
  },
  {
    phrase: "すしをたべますか",
    transcriptionRu: "су~си~о та~бэ~ма~с~ка",
    translationRu: "Будешь есть суши?",
    transcriptionEn: "su~shi~o ta~be~ma~su~ka",
    translationEn: "Will you eat sushi?",
    wordsRu: [
      "すし (sushi) - суши",
      "を (o) - частица вин. падежа",
      "たべます (tabemasu) - есть (вежл.)",
      "か (ka) - вопрос",
    ],
    wordsEn: [
      "すし (sushi) - sushi",
      "を (o) - object marker",
      "たべます (tabemasu) - eat (polite)",
      "か (ka) - question",
    ],
  },
  {
    phrase: "いただきます",
    transcriptionRu: "и~та~да~ки~ма~с",
    translationRu: "Приятного аппетита (перед едой)",
    transcriptionEn: "i~ta~da~ki~ma~su",
    translationEn: "Let's eat / bon appétit",
    wordsRu: ["いただきます (itadakimasu) - (формула перед едой)"],
    wordsEn: ["いただきます (itadakimasu) - (phrase before eating)"],
  },
  {
    phrase: "ごちそうさまでした",
    transcriptionRu: "го~ти~со~у~са~ма~де~си~та",
    translationRu: "Спасибо за угощение (после еды)",
    transcriptionEn: "go~chi~so~u~sa~ma~de~shi~ta",
    translationEn: "Thank you for the meal",
    wordsRu: [
      "ごちそうさまでした (gochisousama deshita) - (формула после еды)",
    ],
    wordsEn: [
      "ごちそうさまでした (gochisousama deshita) - (phrase after eating)",
    ],
  },
  {
    phrase: "わたしのなまえはさくらです",
    transcriptionRu: "ва~та~си~но на~ма~э~ва са~ку~ра дэ~с",
    translationRu: "Меня зовут Сакура",
    transcriptionEn: "wa~ta~shi no na~ma~e wa sa~ku~ra de~su",
    translationEn: "My name is Sakura",
    wordsRu: [
      "わたし (watashi) - я",
      "の (no) - частица принадлежности",
      "なまえ (namae) - имя",
      "は (wa) - частица темы",
      "さくら (Sakura) - Сакура",
      "です (desu) - глагол-связка",
    ],
    wordsEn: [
      "わたし (watashi) - I",
      "の (no) - possessive particle",
      "なまえ (namae) - name",
      "は (wa) - topic particle",
      "さくら (Sakura) - Sakura",
      "です (desu) - am/is",
    ],
  },
  {
    phrase: "おはようございます",
    transcriptionRu: "о~ха~йо~у го~за~й~ма~с",
    translationRu: "Доброе утро",
    transcriptionEn: "o~ha~yo~u go~za~i~ma~su",
    translationEn: "Good morning",
    wordsRu: [
      "おはよう (ohayou) - доброе утро (неформ.)",
      "ございます (gozaimasu) - вежливое окончание",
    ],
    wordsEn: [
      "おはよう (ohayou) - good morning (casual)",
      "ございます (gozaimasu) - polite suffix",
    ],
  },
  {
    phrase: "こんにちわ",
    transcriptionRu: "ко~н~ни~чи~ва",
    translationRu: "Добрый день",
    transcriptionEn: "ko~n~ni~chi~wa",
    translationEn: "Hello / Good afternoon",
    wordsRu: ["こんにちは (konnichiwa) - добрый день"],
    wordsEn: ["こんにちは (konnichiwa) - hello / good afternoon"],
  },
  {
    phrase: "こんばんは",
    transcriptionRu: "ко~н~ба~н~ва",
    translationRu: "Добрый вечер",
    transcriptionEn: "ko~n~ban~wa",
    translationEn: "Good evening",
    wordsRu: ["こんばんは (konbanwa) - добрый вечер"],
    wordsEn: ["こんばんは (konbanwa) - good evening"],
  },
  {
    phrase: "さようなら",
    transcriptionRu: "са~йо~у~на~ра",
    translationRu: "До свидания",
    transcriptionEn: "sa~yo~u~na~ra",
    translationEn: "Goodbye",
    wordsRu: ["さようなら (sayounara) - до свидания"],
    wordsEn: ["さようなら (sayounara) - goodbye"],
  },
  {
    phrase: "ありがとう",
    transcriptionRu: "а~ри~га~то",
    translationRu: "Спасибо",
    transcriptionEn: "a~ri~ga~to",
    translationEn: "Thank you",
    wordsRu: ["ありがとう (arigatou) - спасибо"],
    wordsEn: ["ありがとう (arigatou) - thank you"],
  },
  {
    phrase: "すみません",
    transcriptionRu: "су~ми~ма~сэн",
    translationRu: "Извините / Простите",
    transcriptionEn: "su~mi~ma~sen",
    translationEn: "Excuse me / I'm sorry",
    wordsRu: ["すみません (sumimasen) - извините / простите"],
    wordsEn: ["すみません (sumimasen) - excuse me / I'm sorry"],
  },
  {
    phrase: "がんばってください",
    transcriptionRu: "га~н~ба~ттэ ку~да~са~й",
    translationRu: "Удачи / Постарайся!",
    transcriptionEn: "ga~n~ba~tte ku~da~sa~i",
    translationEn: "Do your best / Good luck",
    wordsRu: [
      "がんばって (ganbatte) - старайся / держись",
      "ください (kudasai) - пожалуйста (вежл.)",
    ],
    wordsEn: [
      "がんばって (ganbatte) - do your best / hang in there",
      "ください (kudasai) - please (polite request)",
    ],
  },
  {
    phrase: "だいじょうぶですか",
    transcriptionRu: "да~й~дзё~у~бу дэ~с~ка",
    translationRu: "Всё в порядке?",
    transcriptionEn: "da~i~jo~u~bu de~su~ka",
    translationEn: "Are you okay?",
    wordsRu: [
      "だいじょうぶ (daijoubu) - всё в порядке",
      "です (desu) - глагол-связка",
      "か (ka) - вопрос",
    ],
    wordsEn: [
      "だいじょうぶ (daijoubu) - all right / ok",
      "です (desu) - is",
      "か (ka) - question",
    ],
  },
  {
    phrase: "いってきます",
    transcriptionRu: "и~т~тэ~ки~ма~с",
    translationRu: "Я пошёл (говорят, уходя из дома)",
    transcriptionEn: "i~t~te~ki~ma~su",
    translationEn: "I'm off / I'll go and come back",
    wordsRu: ["いってきます (ittekimasu) - (дословно «уйду и вернусь»)"],
    wordsEn: ["いってきます (ittekimasu) - (lit. 'I will go and come back')"],
  },
];
