// exercises/phrase_practice/katakana_phrases.js

const katakanaPhrases = [
  {
    phrase: "アイスクリームがすきです",
    transcriptionRu: "а~и~су~ку~ри~му га су~ки дэ~с",
    translationRu: "Я люблю мороженое",
    transcriptionEn: "a~i~su~ku~ri~mu ga su~ki de~su",
    translationEn: "I like ice cream",
  },
  {
    phrase: "コーヒーをのみます",
    transcriptionRu: "ко~о~хи~о но~ми~ма~с",
    translationRu: "Я пью кофе",
    transcriptionEn: "ko~o~hi~o no~mi~ma~su",
    translationEn: "I drink coffee",
  },
  {
    phrase: "ピザはいかがですか",
    transcriptionRu: "пи~дза ва и~ка~га дэ~с~ка",
    translationRu: "Как насчёт пиццы?",
    transcriptionEn: "pi~za wa i~ka~ga de~su~ka",
    translationEn: "How about pizza?",
  },
  {
    phrase: "テレビをみます",
    transcriptionRu: "тэ~рэ~би о ми~ма~с",
    translationRu: "Я смотрю телевизор",
    transcriptionEn: "te~re~bi o mi~ma~su",
    translationEn: "I watch TV",
  },
  {
    phrase: "ニュースはおもしろいです",
    transcriptionRu: "ню~су ва о~мо~си~ро~й дэ~с",
    translationRu: "Новости интересные",
    transcriptionEn: "nyu~su wa o~mo~shi~ro~i de~su",
    translationEn: "The news is interesting",
  },
  {
    phrase: "カメラをかいました",
    transcriptionRu: "ка~ме~ра о ка~и~ма~си~та",
    translationRu: "Я купил(а) камеру",
    transcriptionEn: "ka~me~ra o ka~i~ma~shi~ta",
    translationEn: "I bought a camera",
  },
  {
    phrase: "ゲームをしますか",
    transcriptionRu: "гэ~му о си~ма~с~ка",
    translationRu: "Будем играть в игру?",
    transcriptionEn: "ge~mu o shi~ma~su~ka",
    translationEn: "Shall we play a game?",
  },
  {
    phrase: "タクシーをよびます",
    transcriptionRu: "та~ку~си~ о йо~би~ма~с",
    translationRu: "Я вызову такси",
    transcriptionEn: "ta~ku~shi~ o yo~bi~ma~su",
    translationEn: "I'll call a taxi",
  },
  {
    phrase: "レストランへいきましょう",
    transcriptionRu: "рэ~су~то~ран э и~ки~ма~сё",
    translationRu: "Пойдём в ресторан",
    transcriptionEn: "re~su~to~ran e i~ki~ma~sho",
    translationEn: "Let's go to a restaurant",
  },
  {
    phrase: "パンはありますか",
    transcriptionRu: "пан ва а~ри~ма~с~ка",
    translationRu: "У вас есть хлеб?",
    transcriptionEn: "pan wa a~ri~ma~su~ka",
    translationEn: "Do you have bread?",
  },
  {
    phrase: "ハンバーガーをつくります",
    transcriptionRu: "ха~н~ба~га~ о цу~ку~ри~ма~с",
    translationRu: "Я сделаю гамбургер",
    transcriptionEn: "ha~n~ba~ga~ o tsu~ku~ri~ma~su",
    translationEn: "I'm going to make a hamburger",
  },
  {
    phrase: "メニューをください",
    transcriptionRu: "мэ~ню о ку~да~са~й",
    translationRu: "Дайте, пожалуйста, меню",
    transcriptionEn: "me~nyu o ku~da~sa~i",
    translationEn: "Could I have the menu, please?",
  },
  {
    phrase: "ノートパソコンがほしいです",
    transcriptionRu: "но~о~то па~со~кон га хо~си~й дэ~с",
    translationRu: "Я хочу ноутбук",
    transcriptionEn: "no~o~to pa~so~kon ga ho~shi~i de~su",
    translationEn: "I want a laptop",
  },
  {
    phrase: "コンビニはどこですか",
    transcriptionRu: "ко~н~би~ни ва до~ко дэ~с~ка",
    translationRu: "Где находится магазин 'комбини'?",
    transcriptionEn: "ko~n~bi~ni wa do~ko de~su~ka",
    translationEn: "Where is the convenience store?",
  },
  {
    phrase: "カラオケにいきましょう",
    transcriptionRu: "ка~ра~о~кэ ни и~ки~ма~шо",
    translationRu: "Пойдём в караоке",
    transcriptionEn: "ka~ra~o~ke ni i~ki~ma~sho",
    translationEn: "Let's go to karaoke",
  },
];
