const hiraganaData = [
  { symbol: "あ", katakana: "ア", russian: "а", english: "a", reading: "a/а" },
  { symbol: "い", katakana: "イ", russian: "и", english: "i", reading: "i/и" },
  { symbol: "う", katakana: "ウ", russian: "у", english: "u", reading: "u/у" },
  { symbol: "え", katakana: "エ", russian: "э", english: "e", reading: "e/э" },
  { symbol: "お", katakana: "オ", russian: "о", english: "o", reading: "o/о" },
  { symbol: "か", katakana: "カ", russian: "ка", english: "ka", reading: "ka/ка" },
  { symbol: "が", katakana: "ガ", russian: "га", english: "ga", reading: "ga/га" },
  { symbol: "き", katakana: "キ", russian: "ки", english: "ki", reading: "ki/ки" },
  { symbol: "ぎ", katakana: "ギ", russian: "ги", english: "gi", reading: "gi/ги" },
  { symbol: "く", katakana: "ク", russian: "ку", english: "ku", reading: "ku/ку" },
  { symbol: "ぐ", katakana: "グ", russian: "гу", english: "gu", reading: "gu/гу" },
  { symbol: "け", katakana: "ケ", russian: "кэ", english: "ke", reading: "ke/кэ" },
  { symbol: "げ", katakana: "ゲ", russian: "гэ", english: "ge", reading: "ge/гэ" },
  { symbol: "こ", katakana: "コ", russian: "ко", english: "ko", reading: "ko/ко" },
  { symbol: "ご", katakana: "ゴ", russian: "го", english: "go", reading: "go/го" },
  { symbol: "さ", katakana: "サ", russian: "са", english: "sa", reading: "sa/са" },
  { symbol: "ざ", katakana: "ザ", russian: "дза", english: "za", reading: "za/дза" },
  { symbol: "し", katakana: "シ", russian: "си", english: "shi", reading: "shi/си" },
  { symbol: "じ", katakana: "ジ", russian: "дзи", english: "ji", reading: "ji/дзи" },
  { symbol: "す", katakana: "ス", russian: "су", english: "su", reading: "su/су" },
  { symbol: "ず", katakana: "ズ", russian: "дзу", english: "zu", reading: "zu/дзу" },
  { symbol: "せ", katakana: "セ", russian: "сэ", english: "se", reading: "se/сэ" },
  { symbol: "ぜ", katakana: "ゼ", russian: "дзэ", english: "ze", reading: "ze/дзэ" },
  { symbol: "そ", katakana: "ソ", russian: "со", english: "so", reading: "so/со" },
  { symbol: "ぞ", katakana: "ゾ", russian: "дзо", english: "zo", reading: "zo/дзо" },
  { symbol: "た", katakana: "タ", russian: "та", english: "ta", reading: "ta/та" },
  { symbol: "だ", katakana: "ダ", russian: "да", english: "da", reading: "da/да" },
  { symbol: "ち", katakana: "チ", russian: "ти", english: "chi", reading: "chi/ти" },
  { symbol: "ぢ", katakana: "ヂ", russian: "дзи", english: "ji", reading: "ji/дзи" },
  { symbol: "つ", katakana: "ツ", russian: "цу", english: "tsu", reading: "tsu/цу" },
  { symbol: "づ", katakana: "ヅ", russian: "дзу", english: "zu", reading: "zu/дзу" },
  { symbol: "て", katakana: "テ", russian: "тэ", english: "te", reading: "te/тэ" },
  { symbol: "で", katakana: "デ", russian: "дэ", english: "de", reading: "de/дэ" },
  { symbol: "と", katakana: "ト", russian: "то", english: "to", reading: "to/то" },
  { symbol: "ど", katakana: "ド", russian: "до", english: "do", reading: "do/до" },
  { symbol: "な", katakana: "ナ", russian: "на", english: "na", reading: "na/на" },
  { symbol: "に", katakana: "ニ", russian: "ни", english: "ni", reading: "ni/ни" },
  { symbol: "ぬ", katakana: "ヌ", russian: "ну", english: "nu", reading: "nu/ну" },
  { symbol: "ね", katakana: "ネ", russian: "не", english: "ne", reading: "ne/не" },
  { symbol: "の", katakana: "ノ", russian: "но", english: "no", reading: "no/но" },
  { symbol: "は", katakana: "ハ", russian: "ха", english: "ha", reading: "ha/ха" },
  { symbol: "ば", katakana: "バ", russian: "ба", english: "ba", reading: "ba/ба" },
  { symbol: "ぱ", katakana: "パ", russian: "па", english: "pa", reading: "pa/па" },
  { symbol: "ひ", katakana: "ヒ", russian: "хи", english: "hi", reading: "hi/хи" },
  { symbol: "び", katakana: "ビ", russian: "би", english: "bi", reading: "bi/би" },
  { symbol: "ぴ", katakana: "ピ", russian: "пи", english: "pi", reading: "pi/пи" },
  { symbol: "ふ", katakana: "フ", russian: "фу", english: "fu", reading: "fu/фу" },
  { symbol: "ぶ", katakana: "ブ", russian: "бу", english: "bu", reading: "bu/бу" },
  { symbol: "ぷ", katakana: "プ", russian: "пу", english: "pu", reading: "pu/пу" },
  { symbol: "へ", katakana: "ヘ", russian: "хе", english: "he", reading: "he/хе" },
  { symbol: "べ", katakana: "ベ", russian: "бэ", english: "be", reading: "be/бэ" },
  { symbol: "ぺ", katakana: "ペ", russian: "пэ", english: "pe", reading: "pe/пэ" },
  { symbol: "ほ", katakana: "ホ", russian: "хо", english: "ho", reading: "ho/хо" },
  { symbol: "ぼ", katakana: "ボ", russian: "бо", english: "bo", reading: "bo/бо" },
  { symbol: "ぽ", katakana: "ポ", russian: "по", english: "po", reading: "po/по" },
  { symbol: "ま", katakana: "マ", russian: "ма", english: "ma", reading: "ma/ма" },
  { symbol: "み", katakana: "ミ", russian: "ми", english: "mi", reading: "mi/ми" },
  { symbol: "む", katakana: "ム", russian: "му", english: "mu", reading: "mu/му" },
  { symbol: "め", katakana: "メ", russian: "ме", english: "me", reading: "me/ме" },
  { symbol: "も", katakana: "モ", russian: "мо", english: "mo", reading: "mo/мо" },
  { symbol: "や", katakana: "ヤ", russian: "я", english: "ya", reading: "ya/я" },
  { symbol: "ゆ", katakana: "ユ", russian: "ю", english: "yu", reading: "yu/ю" },
  { symbol: "よ", katakana: "ヨ", russian: "ё", english: "yo", reading: "yo/ё" },
  { symbol: "ら", katakana: "ラ", russian: "ра", english: "ra", reading: "ra/ра" },
  { symbol: "り", katakana: "リ", russian: "ри", english: "ri", reading: "ri/ри" },
  { symbol: "る", katakana: "ル", russian: "ру", english: "ru", reading: "ru/ру" },
  { symbol: "れ", katakana: "レ", russian: "ре", english: "re", reading: "re/ре" },
  { symbol: "ろ", katakana: "ロ", russian: "ро", english: "ro", reading: "ro/ро" },
  { symbol: "わ", katakana: "ワ", russian: "ва", english: "wa", reading: "wa/ва" },
  { symbol: "を", katakana: "ヲ", russian: "во", english: "wo", reading: "wo/во" },
  { symbol: "ん", katakana: "ン", russian: "н", english: "n", reading: "n/н" }
];

const hiraganaAndKatakana = [
  { symbol: "あ - ア", russian: "а", english: "a", reading: "a/а" },
  { symbol: "い - イ", russian: "и", english: "i", reading: "i/и" },
  { symbol: "う - ウ", russian: "у", english: "u", reading: "u/у" },
  { symbol: "え - エ", russian: "э", english: "e", reading: "e/э" },
  { symbol: "お - オ", russian: "о", english: "o", reading: "o/о" },

  { symbol: "か - カ", russian: "ка", english: "ka", reading: "ka/ка" },
  { symbol: "が - ガ", russian: "га", english: "ga", reading: "ga/га" },
  { symbol: "き - キ", russian: "ки", english: "ki", reading: "ki/ки" },
  { symbol: "ぎ - ギ", russian: "ги", english: "gi", reading: "gi/ги" },
  { symbol: "く - ク", russian: "ку", english: "ku", reading: "ku/ку" },
  { symbol: "ぐ - グ", russian: "гу", english: "gu", reading: "gu/гу" },
  { symbol: "け - ケ", russian: "кэ", english: "ke", reading: "ke/кэ" },
  { symbol: "げ - ゲ", russian: "гэ", english: "ge", reading: "ge/гэ" },
  { symbol: "こ - コ", russian: "ко", english: "ko", reading: "ko/ко" },
  { symbol: "ご - ゴ", russian: "го", english: "go", reading: "go/го" },

  { symbol: "さ - サ", russian: "са", english: "sa", reading: "sa/са" },
  { symbol: "ざ - ザ", russian: "дза", english: "za", reading: "za/дза" },
  { symbol: "し - シ", russian: "си", english: "shi", reading: "shi/си" },
  { symbol: "じ - ジ", russian: "дзи", english: "ji", reading: "ji/дзи" },
  { symbol: "す - ス", russian: "су", english: "su", reading: "su/су" },
  { symbol: "ず - ズ", russian: "дзу", english: "zu", reading: "zu/дзу" },
  { symbol: "せ - セ", russian: "сэ", english: "se", reading: "se/сэ" },
  { symbol: "ぜ - ゼ", russian: "дзэ", english: "ze", reading: "ze/дзэ" },
  { symbol: "そ - ソ", russian: "со", english: "so", reading: "so/со" },
  { symbol: "ぞ - ゾ", russian: "дзо", english: "zo", reading: "zo/дзо" },

  { symbol: "た - タ", russian: "та", english: "ta", reading: "ta/та" },
  { symbol: "だ - ダ", russian: "да", english: "da", reading: "da/да" },
  { symbol: "ち - チ", russian: "ти", english: "chi", reading: "chi/ти" },
  { symbol: "ぢ - ヂ", russian: "дзи", english: "ji", reading: "ji/дзи" },
  { symbol: "つ - ツ", russian: "цу", english: "tsu", reading: "tsu/цу" },
  { symbol: "づ - ヅ", russian: "дзу", english: "zu", reading: "zu/дзу" },
  { symbol: "て - テ", russian: "тэ", english: "te", reading: "te/тэ" },
  { symbol: "で - デ", russian: "дэ", english: "de", reading: "de/дэ" },
  { symbol: "と - ト", russian: "то", english: "to", reading: "to/то" },
  { symbol: "ど - ド", russian: "до", english: "do", reading: "do/до" },

  { symbol: "な - ナ", russian: "на", english: "na", reading: "na/на" },
  { symbol: "に - ニ", russian: "ни", english: "ni", reading: "ni/ни" },
  { symbol: "ぬ - ヌ", russian: "ну", english: "nu", reading: "nu/ну" },
  { symbol: "ね - ネ", russian: "не", english: "ne", reading: "ne/не" },
  { symbol: "の - ノ", russian: "но", english: "no", reading: "no/но" },

  { symbol: "は - ハ", russian: "ха", english: "ha", reading: "ha/ха" },
  { symbol: "ば - バ", russian: "ба", english: "ba", reading: "ba/ба" },
  { symbol: "ぱ - パ", russian: "па", english: "pa", reading: "pa/па" },
  { symbol: "ひ - ヒ", russian: "хи", english: "hi", reading: "hi/хи" },
  { symbol: "び - ビ", russian: "би", english: "bi", reading: "bi/би" },
  { symbol: "ぴ - ピ", russian: "пи", english: "pi", reading: "pi/пи" },
  { symbol: "ふ - フ", russian: "фу", english: "fu", reading: "fu/фу" },
  { symbol: "ぶ - ブ", russian: "бу", english: "bu", reading: "bu/бу" },
  { symbol: "ぷ - プ", russian: "пу", english: "pu", reading: "pu/пу" },
  { symbol: "へ - ヘ", russian: "хе", english: "he", reading: "he/хе" },
  { symbol: "べ - ベ", russian: "бэ", english: "be", reading: "be/бэ" },
  { symbol: "ぺ - ペ", russian: "пэ", english: "pe", reading: "pe/пэ" },
  { symbol: "ほ - ホ", russian: "хо", english: "ho", reading: "ho/хо" },
  { symbol: "ぼ - ボ", russian: "бо", english: "bo", reading: "bo/бо" },
  { symbol: "ぽ - ポ", russian: "по", english: "po", reading: "po/по" },

  { symbol: "ま - マ", russian: "ма", english: "ma", reading: "ma/ма" },
  { symbol: "み - ミ", russian: "ми", english: "mi", reading: "mi/ми" },
  { symbol: "む - ム", russian: "му", english: "mu", reading: "mu/му" },
  { symbol: "め - メ", russian: "ме", english: "me", reading: "me/ме" },
  { symbol: "も - モ", russian: "мо", english: "mo", reading: "mo/мо" },

  { symbol: "や - ヤ", russian: "я", english: "ya", reading: "ya/я" },
  { symbol: "ゆ - ユ", russian: "ю", english: "yu", reading: "yu/ю" },
  { symbol: "よ - ヨ", russian: "ё", english: "yo", reading: "yo/ё" },

  { symbol: "ら - ラ", russian: "ра", english: "ra", reading: "ra/ра" },
  { symbol: "り - リ", russian: "ри", english: "ri", reading: "ri/ри" },
  { symbol: "る - ル", russian: "ру", english: "ru", reading: "ru/ру" },
  { symbol: "れ - レ", russian: "ре", english: "re", reading: "re/ре" },
  { symbol: "ろ - ロ", russian: "ро", english: "ro", reading: "ro/ро" },

  { symbol: "わ - ワ", russian: "ва", english: "wa", reading: "wa/ва" },
  { symbol: "を - ヲ", russian: "во", english: "wo", reading: "wo/во" },
  { symbol: "ん - ン", russian: "н", english: "n", reading: "n/н" },

  // Сочетания хираганы и катаканы
  { symbol: "きゃ - キャ", russian: "кя", english: "kya", reading: "kya/кя" },
  { symbol: "きゅ - キュ", russian: "кю", english: "kyu", reading: "kyu/кю" },
  { symbol: "きょ - キョ", russian: "кё", english: "kyo", reading: "kyo/кё" },

  { symbol: "しゃ - シャ", russian: "ся", english: "sha", reading: "sha/ся" },
  { symbol: "しゅ - シュ", russian: "сю", english: "shu", reading: "shu/сю" },
  { symbol: "しょ - ショ", russian: "сё", english: "sho", reading: "sho/сё" },

  { symbol: "ちゃ - チャ", russian: "тя", english: "cha", reading: "cha/тя" },
  { symbol: "ちゅ - チュ", russian: "тю", english: "chu", reading: "chu/тю" },
  { symbol: "ちょ - チョ", russian: "тё", english: "cho", reading: "cho/тё" },

  { symbol: "にゃ - ニャ", russian: "ня", english: "nya", reading: "nya/ня" },
  { symbol: "にゅ - ニュ", russian: "ню", english: "nyu", reading: "nyu/ню" },
  { symbol: "にょ - ニョ", russian: "нё", english: "nyo", reading: "nyo/нё" },

  { symbol: "ひゃ - ヒャ", russian: "хя", english: "hya", reading: "hya/хя" },
  { symbol: "ひゅ - ヒュ", russian: "хю", english: "hyu", reading: "hyu/хю" },
  { symbol: "ひょ - ヒョ", russian: "хё", english: "hyo", reading: "hyo/хё" },

  { symbol: "みゃ - ミャ", russian: "мя", english: "mya", reading: "mya/мя" },
  { symbol: "みゅ - ミュ", russian: "мю", english: "myu", reading: "myu/мю" },
  { symbol: "みょ - ミョ", russian: "мё", english: "myo", reading: "myo/мё" },

  { symbol: "りゃ - リャ", russian: "ря", english: "rya", reading: "rya/ря" },
  { symbol: "りゅ - リュ", russian: "рю", english: "ryu", reading: "ryu/рю" },
  { symbol: "りょ - リョ", russian: "рё", english: "ryo", reading: "ryo/рё" },

  { symbol: "ぎゃ - ギャ", russian: "гя", english: "gya", reading: "gya/гя" },
  { symbol: "ぎゅ - ギュ", russian: "гю", english: "gyu", reading: "gyu/гю" },
  { symbol: "ぎょ - ギョ", russian: "гё", english: "gyo", reading: "gyo/гё" },

  { symbol: "じゃ - ジャ", russian: "дзя", english: "ja", reading: "ja/дзя" },
  { symbol: "じゅ - ジュ", russian: "дзю", english: "ju", reading: "ju/дзю" },
  { symbol: "じょ - ジョ", russian: "дзё", english: "jo", reading: "jo/дзё" },

  { symbol: "びゃ - ビャ", russian: "бя", english: "bya", reading: "bya/бя" },
  { symbol: "びゅ - ビュ", russian: "бю", english: "byu", reading: "byu/бю" },
  { symbol: "びょ - ビョ", russian: "бё", english: "byo", reading: "byo/бё" },

  { symbol: "ぴゃ - ピャ", russian: "пя", english: "pya", reading: "pya/пя" },
  { symbol: "ぴゅ - ピュ", russian: "пю", english: "pyu", reading: "pyu/пю" },
  { symbol: "ぴょ - ピョ", russian: "пё", english: "pyo", reading: "pyo/пё" },

  // Сдвоенные согласные (цыки) — хирагана и катакана
  { symbol: "っか - ッカ", russian: "кка", english: "kka", reading: "kka/кка" },
  { symbol: "っき - ッキ", russian: "кки", english: "kki", reading: "kki/кки" },
  { symbol: "っく - ック", russian: "кку", english: "kku", reading: "kku/кку" },
  { symbol: "っけ - ッケ", russian: "ккэ", english: "kke", reading: "kke/ккэ" },
  { symbol: "っこ - ッコ", russian: "кко", english: "kko", reading: "kko/кко" },

  { symbol: "っさ - ッサ", russian: "сса", english: "ssa", reading: "ssa/сса" },
  { symbol: "っし - ッシ", russian: "сси", english: "sshi", reading: "sshi/сси" },
  { symbol: "っす - ッス", russian: "ссу", english: "ssu", reading: "ssu/ссу" },
  { symbol: "っせ - ッセ", russian: "ссэ", english: "sse", reading: "sse/ссэ" },
  { symbol: "っそ - ッソ", russian: "ссо", english: "sso", reading: "sso/ссо" },

  { symbol: "った - ッタ", russian: "тта", english: "tta", reading: "tta/тта" },
  { symbol: "っち - ッチ", russian: "тти", english: "tchi", reading: "tchi/тти" },
  { symbol: "っつ - ッツ", russian: "ттсу", english: "ttsu", reading: "ttsu/ттсу" },
  { symbol: "って - ッテ", russian: "ттэ", english: "tte", reading: "tte/ттэ" },
  { symbol: "っと - ット", russian: "тто", english: "tto", reading: "tto/тто" },

  { symbol: "っぱ - ッパ", russian: "ппа", english: "ppa", reading: "ppa/ппа" },
  { symbol: "っぴ - ッピ", russian: "ппи", english: "ppi", reading: "ppi/ппи" },
  { symbol: "っぷ - ップ", russian: "ппу", english: "ppu", reading: "ppu/ппу" },
  { symbol: "っぺ - ッペ", russian: "ппэ", english: "ppe", reading: "ppe/ппэ" },
  { symbol: "っぽ - ッポ", russian: "ппо", english: "ppo", reading: "ppo/ппо" },
];
